apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: myapi-dev
data:
  DATABASE_URL: "postgresql://myuser:password@postgres-service.myapi-dev.svc.cluster.local:5432/mydatabase"
  JWT_ALGORITHM: "HS256"
  JWT_EXPIRE_MINUTES: "30"