apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api
  namespace: myapi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      labels:
        app: python-api
    spec:
      serviceAccountName: python-api-sa
      containers:
      - name: python-api
        image: dockermohcine/my-python-api:1.1.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "1Gi"  
            cpu: "500m"      
          limits:
            memory: "2Gi"   
            cpu: "1"  
        env:
        - name: VAULT_ADDR
          value: "http://vault.myapi-dev.svc.cluster.local:8200" 
        - name: VAULT_ROLE
          value: "fastapi-app"
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: DATABASE_URL
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: JWT_SECRET_KEY
        - name: JWT_ALGORITHM
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: JWT_ALGORITHM
        - name: JWT_EXPIRE_MINUTES
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: JWT_EXPIRE_MINUTES