apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  DATABASE_URL: {{ .Values.config.DATABASE_URL | quote }}
  JWT_ALGORITHM: {{ .Values.config.JWT_ALGORITHM | quote }}
  JWT_EXPIRE_MINUTES: {{ .Values.config.JWT_EXPIRE_MINUTES | quote }}
  VAULT_ADDR: {{ .Values.config.VAULT_ADDR | quote }}
  VAULT_ROLE: {{ .Values.config.VAULT_ROLE | quote}}
